/**
 * @file jkr/declaration/swizzle.hpp
 */

#ifndef JKR_SWIZZLE_HPP
#define JKR_SWIZZLE_HPP

#define JKR_SWIZZLE_COMBINATION_VEC1(a) \
  vec<1, T> a() const { return vec<1, T>(a); }

#define JKR_SWIZZLE_COMBINATION_VEC2(a,b) \
  vec<2, T> a##b() const { return vec<2, T>(a,b); }

#define JKR_SWIZZLE_COMBINATION_VEC3(a,b,c) \
  vec<3, T> a##b##c() const { return vec<3, T>(a,b,c); }

// To Vector 2

// Expands to the combinations {AB,BA}
#define JKR_SWIZZLE_VEC2_HELPER(a,b) \
  JKR_SWIZZLE_COMBINATION_VEC2(a,b) \
  JKR_SWIZZLE_COMBINATION_VEC2(b,a)
  
#define JKR_VEC2_SWIZZLE_VEC2(a,b) \
  JKR_SWIZZLE_COMBINATION_VEC2(a,a) \
  JKR_SWIZZLE_VEC2_HELPER(a,b) \
  JKR_SWIZZLE_COMBINATION_VEC2(b,b)

#define JKR_VEC3_SWIZZLE_VEC2(a,b,c) \
  JKR_VEC2_SWIZZLE_VEC2(a,b) \
  JKR_SWIZZLE_VEC2_HELPER(a,c) \
  JKR_SWIZZLE_VEC2_HELPER(b,c) \
  JKR_SWIZZLE_COMBINATION_VEC2(c,c)

#define JKR_VEC4_SWIZZLE_VEC2(a,b,c,d) \
  JKR_VEC3_SWIZZLE_VEC2(a,b,c) \
  JKR_SWIZZLE_VEC2_HELPER(a,d) \
  JKR_SWIZZLE_VEC2_HELPER(b,d) \
  JKR_SWIZZLE_VEC2_HELPER(c,d) \
  JKR_SWIZZLE_COMBINATION_VEC2(d,d)

// To Vector 3
// Expands to combinations {AAB,ABA,ABB,BAA,BAB,BBA}
#define JKR_SWIZZLE_VEC3_HELPER_AB(a,b) \
  JKR_SWIZZLE_COMBINATION_VEC3(a,a,b) \
  JKR_SWIZZLE_COMBINATION_VEC3(a,b,a) \
  JKR_SWIZZLE_COMBINATION_VEC3(a,b,b) \
  JKR_SWIZZLE_COMBINATION_VEC3(b,a,a) \
  JKR_SWIZZLE_COMBINATION_VEC3(b,a,b) \
  JKR_SWIZZLE_COMBINATION_VEC3(b,b,a) 

// Expands to combinations {ABC,ACB,BAC,BCA,CAB,CBA}
#define JKR_SWIZZLE_VEC3_HELPER_ABC(a,b,c) \
  JKR_SWIZZLE_COMBINATION_VEC3(a,b,c) \
  JKR_SWIZZLE_COMBINATION_VEC3(a,c,b) \
  JKR_SWIZZLE_COMBINATION_VEC3(b,a,c) \
  JKR_SWIZZLE_COMBINATION_VEC3(b,c,a) \
  JKR_SWIZZLE_COMBINATION_VEC3(c,a,b) \
  JKR_SWIZZLE_COMBINATION_VEC3(c,b,a) 
  
#define JKR_VEC2_SWIZZLE_VEC3(a,b) \
  JKR_SWIZZLE_COMBINATION_VEC3(a,a,a) \
  JKR_SWIZZLE_VEC3_HELPER_AB(a,b) \
  JKR_SWIZZLE_COMBINATION_VEC3(b,b,b) 

#define JKR_VEC3_SWIZZLE_VEC3(a,b,c) \
  JKR_VEC2_SWIZZLE_VEC3(a,b) \
  JKR_SWIZZLE_VEC3_HELPER_AB(a,c) \
  JKR_SWIZZLE_VEC3_HELPER_AB(b,c) \
  JKR_SWIZZLE_VEC3_HELPER_ABC(a,b,c) \
  JKR_SWIZZLE_COMBINATION_VEC3(c,c,c) 

#define JKR_VEC4_SWIZZLE_VEC3(a,b,c,d) \
  JKR_VEC3_SWIZZLE_VEC3(a,b,c) \
  JKR_SWIZZLE_VEC3_HELPER_AB(a,d) \
  JKR_SWIZZLE_VEC3_HELPER_AB(b,d) \
  JKR_SWIZZLE_VEC3_HELPER_AB(c,d) \
  JKR_SWIZZLE_VEC3_HELPER_ABC(a,b,d) \
  JKR_SWIZZLE_VEC3_HELPER_ABC(a,c,d) \
  JKR_SWIZZLE_VEC3_HELPER_ABC(b,c,d) \
  JKR_SWIZZLE_COMBINATION_VEC3(d,d,d) 

#endif